site_name: Apunts 0223 - Aplicacions Ofimàtiques
site_description: Publicació progressiva des d'un sol repositori
site_url: https://github.com/jpardo20/aof-apunts


# mkdocs.yml
nav:
  - Inici: index.md
  - Continguts: continguts.md
  - UD01: unitats-didactiques/ud01-iao/aof-ud01-introduccion-a-aplicaciones-ofimaticas.md


# nav:
#   - Inici: index.md
#   - Continguts: continguts.md
#   - UD01:
#       - Introducció: unitats-didactiques/ud01-iao/aof-ud01-introduccio-a-aplicacions-ofimatiques.md
#   - UD02:
#       - Organització: unitats-didactiques/ud02-oiicap/aof-ud02-organizacio-individual-i-collectiva-amb-projectes.md


theme:
  name: material
  language: ca
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - def_list
