site_name: Mòdul 0223 - Aplicacions Ofimàtiques
site_description: Publicació progressiva des d'un sol repositori
site_url: https://github.com/jpardo20/aof-apunts


# mkdocs.yml
nav:
  - Inici: index.md
  - Continguts: continguts.md
  - Tema 1:
      - Introducció: unitats-didactiques/ud01-iao/index.md
      - Activitats avaluables 01: unitats-didactiques/ud01-iao/aof-ud01-actividades-evaluables-01.md
      - Glossari: unitats-didactiques/ud01-iao/aof-ud01-glosario.md

# nav:
#   - Inici: index.md
#   - Continguts: continguts.md
#   - UD01:
#       - Introducció: unitats-didactiques/ud01-iao/index.md
#   - UD02:
#       - Organització: unitats-didactiques/ud02-oiicap/index.md


theme:
  name: material
  language: ca
  features:
    - navigation.indexes     # el títol de secció obre l'index.md
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - def_list

extra_css:
  - assets/styles.css
