name: build-and-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps (pandoc + python libs)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          python -m pip install --upgrade pip
          pip install pyyaml mkdocs mkdocs-material

      - name: Publish selected items
        run: |
          python scripts/publish_selected.py

      - name: Build site
        run: mkdocs build --strict

      - name: Copy 'presentacions' into built site
        run: |
          mkdir -p site/presentacions
          if [ -d "presentacions" ]; then
            # Copy the entire folder (including hidden files) without failing if it's empty
            cp -a presentacions/. site/presentacions/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
